name: Testing

on:
  workflow_run:
    workflows: ["Build"]
    types: [completed]

jobs:
  testing:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-task@v2

      - name: Run unit tests
        run: task test-unit

      - name: Run lint tests
        run: task test-lint

      - name: Run integration tests
        env:
          ZHIPU_API_KEY: test
          GEMINI_API_KEY: ""
        run: task test-integration
