name: Testing

on:
  push:
  pull_request:

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-task@v2

      - name: Run unit tests
        run: task test-unit

      - name: Run lint tests
        run: task test-lint

      - name: Run integration tests
        env:
          ZHIPU_API_KEY: test
          GEMINI_API_KEY: ""
          TEST_HEALTH_TIMEOUT: "600"
          TEST_HEALTH_REQUEST_TIMEOUT: "5"
        run: task test-integration
